install.packages ("gmodels")
install.packages ("MASS")
install.packages ("ggplot2")
install.packages("vcd")
install.packages("Hmisc")
install.packages("car")
install.packages("corrplot")
install.packages("broom")
install.packages("pscl")
install.packages("mlogit")
install.packages("logreg")
install.packages("caret")
install.packages("dplyr")
library(dplyr)
library(caret)
library(logreg)
library(mlogit)
library(pscl)
library(broom)
library(corrplot)
library(car)
library(Hmisc)
library (ggplot2);
library(vcd);
library (gmodels); 
library (MASS);
library(foreign)